### ISSUE TITLE
텐서플로우, Azure Cloud 핵심 기능 적용 및 구현 여부가 Key. 

### ISSUE THREAD

**Issue by faci-df** [faci-df/deepFlowers#11]
다른 기술 이슈는 현재 시점에 크게 신경 안 써도 됨.
핵심 기능이란 
Image Input -> 처리(꽃 이름 판단) -> 결과값 출력
 (정확도는 높지 않아도 됨. 수긍할 수 있는 수준의 인식률.
향후 발전가능성이 보이면 상관 없음.)

만약 핵심기능 구현여부가 미지수라면 프로젝트 도중에 주제를 바꿔야 할 수도 있음.

**Comment by mioksong** [comment]
네
