### ISSUE TITLE
스펙문서_송미옥(5.성능요구사항)

### ISSUE THREAD

**Issue by mioksong** [faci-df/deepFlowers#22]
[스펙문서_송미옥.docx](https://github.com/faci-df/deepFlowers/files/864936/_.docx)

5.	성능 요구사항
<성능목표를 가능한 수치화하여 도출한다. 이슈가 될만한 핵심적인 기능의 성능 속성을 설명한다. >
5.1	작업처리량
<일정 시간내 수행한 작업량>
5.1.1	시스템은 정상 상태에서 사용자의 건별 요청에 대한 처리를 3초 이내에 해야한다.
5.1.2	시스템은 최대 부하 상태에서 초당 50건의 사용자의 요청을 처리할 수 있어야 한다.
5.2	동시 세션
5.2.1	시스템의 전체 사용자 수는 최대 1000명으로 한다.
5.2.2	시스템은 정상 상태에서 최대 100명의 동시 사용자를 수용해야 한다.
5.3	대응시간
<처리시간 >
5.3.1	시스템은 정상 상태에서 사용자의 질의요청에 대한 결과 페이지를 화면에 출력할 때, 4초 이내에 보여주어야 한다.
5.3.2	평균 응답시간은 시스템을 사용하는 동시 사용자가 최대 사용자 수의 90%를 초과하는 경우에는 적용되지 않는다.
5.4	성능 종속 관계
<하나 이상의 성능이 서로 종속적일 경우 연관관계를 기술한다.> 
5.4.1	평균처리시간은 동시세션에 종속적이다.
5.5	기타 성능 요구사항
<메모리, 디스크공간 요구사항, DB 최대 rows와 같은 기타 성능 관련 요구사항을 기술한다. >
<자원 사용률>
10.5.1	시스템의 메모리는 최대 부하 시점에서도 90%이상은 사용되지 않아야 한다.
10.5.2	시스템은 정상 상태에서 백그라운드 작업을 위하여 CPU, GPU를 50% 이하로 사용해야 한다.
10.5.3	입출력 대기상태의 CPU사용률 (I/Owaiting)은 10% 이내로 사용하도록 한다.
10.5.4	시스템의 설치 전의 여유 디스크공간은 50% 이상을 유지하도록 한다.

**Comment by JongHeeYoon** [comment]
## 5.성능 요구사항

<성능목표를 가능한 수치화하여 도출한다. 이슈가 될만한 핵심적인 기능의 성능 속성을 설명한다. >
<스마트폰 기본사항>
-  삼성 갤럭시 S6 엣지(Samsung Galaxy S6 Edge 이상 버전
-  운영체제/소프트웨어 : 안드로이드 6.0.1 마시멜로 이상 버전
-  모델명 : SM-G925S (Korea SKT) 이후 버전 
- AP(Application Processor : 중앙처리장치) : 삼성전자 엑시노트 7 옥타
- CPU(Central Processing Unit) : 
ARM 홀딩스 코텍스-A57 2.1 GHz 쿼드 코어
ARM 홀딩스 코텍스-A53 아키텍처 1.5 GHz 쿼드 코어
(big.LITTLE HMP)
- GPU(Graphics Processing Unit) : 
	ARM 홀딩스 말리 T760 MP8 700 MHz
- RAM(Random Access Memory) : 3GB
- 저장용량 : 64GB (UFS : Unix File System)

5.1	작업처리량
<일정 시간내 수행한 작업량>
5.1.1	Deep Flowers 어플리케이션은 스마트폰에서 단독 실행을 했을 경우, 꽃검색 요청에 대한 처리를 3초 이내에 해야 한다.
5.1.2	Deep Flowers 어플리케이션은 스마트폰에서 3개이상의 어플리케이션이 실행되고 있는 경우에도 꽃검색 요청에 대한 처리를 3초 이내에 해야한다.
5.2	기타 성능 요구사항
<메모리, 디스크공간 요구사항, DB 최대 rows와 같은 기타 성능 관련 요구사항을 기술한다. >

< 메모리, 디스크공간 요구사항>
5.2.1	Deep Flowers 어플리케이션의 사용 시 필요한 메모리는 300MB 필요하다.
5.2.2	Deep Flowers 어플리케이션의 사용 디스크 공간은 300MB 정도로 예상하며, 스마트폰의 디스크 공간은 스마트폰기종의 기본사양만 충족하면 된다.

<자원 사용률>
5.2.3	스마트폰 메모리(전체 3GB 중 예비공간 392MB포함)를 300MB 이상 사용되지 않아야 한다.
5.2.4	Deep Flowers 어플리케이션을 실행만 해 놓은 경우, CPU 사용량은 0MB, RAM 은 200MB 이하로 사용되어야 한다.(권장사용량 : 160MB)
5.2.5	Deep Flowers 어플리케이션을 실행하고, 절전모드를 실행하면 RAM은 100MB 미만으로 사용되어야한다. (권장 사용량 : 11MB~90MB)
