### ISSUE TITLE
MW G 발표자료 리뷰 결과, 17.4.19 14:30

### ISSUE THREAD

**Issue by faci-df** [faci-df/deepFlowers#41]
발표 시나리오를 만들어 이야기 하듯 자연스럽게 진행해야.

구체적인 AI 기술에 대한 설명을 한장, 두장을 할애해서 할 필요 없음. (별첨으로 이동)

전체 발표분량은 4 ~ 5장이면 충분.

연구회를 하게 된 계기 최신 IT Trend(AI etc)에 대한 궁금증/호기심에서 출발해서

이를 해소하기 위해 Deep Flowers 앱개발을 수단으로 선택 하였고

그 과정에서 이슈화 되는 관련 기술(안드로이드, Deep Learning, Mobile Tech 등)을

적절히 연구회 구성원간에 R&R(Role And Responsibility)을 분배해서

일정계획을 가지고 추진해 가고 있다고 설명하면 됨.

향후계획에 대한 설명 포함(iPhone Version Dev etc)

* 청자는(발표를 듣는 사람)은 구체적인 IT 기술에는 큰 관심이 없다는 가정하에.

**Comment by dy8487** [comment]
결국 4~5장으로 줄이란 건가?

**Comment by mioksong** [comment]
본문을 4장으로 하고,뒤에 별첨으로 빼는거죠~
총 장수는 변동없이..
