### ISSUE TITLE
ARM, HAXM 설치 실패 원인

### ISSUE THREAD

**Issue by mioksong** [faci-df/deepFlowers#45]
안드로이드 스튜디오에서 애뮬 실행 시 V3 로 인해 애뮬설치가 안되는 사례가 발생.
개인PC에서 따로 애뮬실행을 다시 해볼 예정.
너무너무 느려서 좀 걱정임.

http://me2.do/FE02csBn

**Comment by jjoomyjjoo** [comment]
우와~
